-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles table (Mock Auth inserts here)
create table if not exists profiles (
  id uuid primary key,
  username text unique,
  display_name text,
  daily_goal_minutes integer default 240,
  theme text default 'dark',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Subjects table
create table if not exists subjects (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  name text not null,
  color text,
  icon text,
  total_chapters integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Chapters table
create table if not exists chapters (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  name text not null,
  status text default 'not_started',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Study Sessions table
create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  subject_id bigint references subjects(id) on delete set null,
  chapter_id bigint references chapters(id) on delete set null,
  date date default current_date,
  start_time text,
  end_time text,
  duration_minutes integer,
  topics text[],
  confidence_rating integer,
  mood text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Exam Targets table
create table if not exists exam_targets (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  name text not null,
  exam_date date,
  subject_ids bigint[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table subjects enable row level security;
alter table chapters enable row level security;
alter table study_sessions enable row level security;
alter table exam_targets enable row level security;

-- Create policies (Allow all for now to support Mock Auth + Realtime)
create policy "Enable all access for all users" on profiles for all using (true);
create policy "Enable all access for all users" on subjects for all using (true);
create policy "Enable all access for all users" on chapters for all using (true);
create policy "Enable all access for all users" on study_sessions for all using (true);
create policy "Enable all access for all users" on exam_targets for all using (true);
